---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: exporter-apps-versions
  strategy:
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: exporter-apps-versions
    spec:
      containers:
        - name: exporter-apps-versions
          image: base.sw.sbc.space/pid/pid_registry/exporter-apps-versions/exporter-apps-versions:0.0.1
          ports:
            - containerPort: 5002
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /PD15versions
              port: 5002
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /PD15versions
              port: 5002
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
            initialDelaySeconds: 10
#          resources:
#            requests:
#              cpu: 500m
#              memory: 1000Mi
#            limits:
#              cpu: 1000m
#              memory: 1000Mi
      imagePullSecrets:
        - name: regcred



#          volumeMounts:
#            - name: config
#              mountPath: /etc/nginx/conf.d/
#      volumes:
#        - name: config
#          configMap:
#            name: my-configmap


---
apiVersion: v1
kind: Service
metadata:
  name: exporter-apps-versions-service
spec:
  type: ClusterIP
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 5002
  selector:
    app: exporter-apps-versions

---
apiVersion: networking.k8s.io/v1
kind: Ingress

metadata:
  name: exporter-apps-versions-ingress
#  namespace: default
spec:
  defaultBackend:
    service:
      name: my-service
      port:
        number: 8080
  rules:
  - host: avorrtest.ru
    http:
      paths:
      - pathType: ImplementationSpecific
        backend:
          service:
            name: exporter-apps-versions-service
            port:
              number: 8080
...