#FROM python:3
#
#ENV TZ=Europe/Moscow
#
#ENV PYTHONWARNINGS="ignore:Unverified HTTPS request"
#
#RUN touch /var/log/cron.log
#
#
#
#
#
#
##RUN set -ex && pip3 install --no-cache --upgrade \
##                                         flask \
##                                         loguru \
##                                         requests \
##                                         paramiko
##                              pyopenssl
#
##COPY . /opt/
#
#
#
#
#RUN set -ex && apt update && apt -y install cron
#
#
#
#
#
## Create the log file to be able to run tail
## Run the command on container startup
##CMD cron && tail -f /var/log/cron.log
#
#
#
#COPY crontab /etc/cron.d/hello-cron
#RUN chmod 0644 /etc/cron.d/hello-cron
#RUN crontab /etc/cron.d/hello-cron
#CMD cron && tail -f /var/log/cron.log
#
#
##CMD ["/usr/local/bin/python3", "/opt/versions-exporter.py"]



FROM python:3
RUN apt-get update && apt-get -y install cron

# Copy hello-cron file to the cron.d directory
COPY hello-cron /etc/cron.d/hello-cron

# Give execution rights on the cron job
RUN chmod 0644 /etc/cron.d/hello-cron

# Create the log file to be able to run tail
RUN touch /var/log/cron.log

# Apply cron job
RUN crontab /etc/cron.d/hello-cron



# Run the command on container startup
CMD cron && tail -f /var/log/cron.log